
#CFILES += ./ucgui394_sample/2dgl_bmpexport.c			# not run, need windows.h
#CFILES += ./ucgui394_sample/2dgl_drawbmp.c				# not run, need windows.h
#CFILES += ./ucgui394_sample/2dgl_drawpolygon.c 		# done
#CFILES += ./ucgui394_sample/2dgl_drawscale.c			# failue, display error
#CFILES += ./ucgui394_sample/aa_hiresantialiasing.c 	# failue, display error
#CFILES += ./ucgui394_sample/aa_hirespixels.c			# failue, display error
#CFILES += ./ucgui394_sample/aa_lines.c					# ok, but too slow
#CFILES += ./ucgui394_sample/basic_hello1.c				# done
#CFILES += ./ucgui394_sample/color_showcolorbar.c		# done
#CFILES += ./ucgui394_sample/cursor_sample.c			# unknow bugs
#CFILES += ./ucgui394_sample/dashboard.c				# lcc compiler error
CFILES += ./ucgui394_sample/dialog_all.c				# failue, sim no response
#CFILES += ./ucgui394_sample/housecontrol.c				# not run, need RTOS.h
#CFILES += ./ucgui394_sample/memdev_autodev.c			# falue, display bugs
#CFILES += ./ucgui394_sample/memdev_banding.c			# done
#CFILES += ./ucgui394_sample/memdev_memdev.c			# !!! fatal error, sim stop
#CFILES += ./ucgui394_sample/mt_multitasking.c			# not run, need RTOS.h
#CFILES += ./ucgui394_sample/touch_sample.c				# failue, sim not response
#CFILES += ./ucgui394_sample/widget_buttonround.c		# failue, memory free error, not response
#CFILES += ./ucgui394_sample/widget_edit.c				# ok, but no fully test, because no keyboard input
#CFILES += ./ucgui394_sample/widget_listboxownerdraw.c	# failue, sim not response
#CFILES += ./ucgui394_sample/widget_listview.c			# failue, sim not response
#CFILES += ./ucgui394_sample/widget_framewin.c			# failue
#CFILES += ./ucgui394_sample/widget_header.c			# failue, corsor display
#CFILES += ./ucgui394_sample/widget_scrollbarmove.c		# ok
#CFILES += ./ucgui394_sample/widget_simplelistbox.c		# ok
#CFILES += ./ucgui394_sample/widget_simpleprogbar.c		# failue, program no response
#CFILES += ./ucgui394_sample/wm_redraw.c				# failue, program no response
#CFILES += ./ucgui394_sample/wm_sample.c				# failue, sim no response
#CFILES += ./ucgui394_sample/xeye.c						# failue, program no response
#CFILES += ./ucgui394_sample/sim_hardkey.c				# error, no SIM.h
#CFILES += ./ucgui394_sample/memdev_drawgraph.c			# done
#CFILES += ./ucgui394_sample/font_Shiftjis.c			# done
#CFILES += ./ucgui394_sample/dialog_slidercolor.c		# failue, program no response
#CFILES += ./ucgui394_sample/dialog_radio.c				# failue, memory free error
#CFILES += ./ucgui394_sample/dialog_messagebox.c		# failue, program no response
