
.PHONY: all
all:
	@echo

.PHONY: clean
clean:
	make -C test1 clean
	make -C test2 clean
	make -C asm_test clean
	make -C ucosii-2.92 clean
	make -C inst_test clean
	make -C pff_test_l32 clean
	make -C gui_test distclean
	make -C setjmp_test clean
	make -C random_test clean
	make -C lib_test clean
	make -C float_test distclean
	make -C fifo_test distclean
	make -C nic_test distclean
	make -C string_test clean
	make -C fdlibm-5.2  clean
	make -C tlb_test clean
	make -C heap_test clean
	make -C ulisp-zero clean
	make -C ucfs clean
	make -C ucgui_no_os distclean
	make -C ucgui_ucosii distclean
	make -C fat_fs distclean
	make -C ugui_example/ clean
