
#CFILES += ./ucgui394_sample/2dgl_bmpexport.c			# compiler error, need windows.h
#CFILES += ./ucgui394_sample/2dgl_drawbmp.c				# compiler error, need windows.h
#CFILES += ./ucgui394_sample/2dgl_drawpolygon.c 		# done
#CFILES += ./ucgui394_sample/2dgl_drawscale.c			# done
#CFILES += ./ucgui394_sample/aa_hiresantialiasing.c		# done
#CFILES += ./ucgui394_sample/aa_hirespixels.c			# done
#CFILES += ./ucgui394_sample/aa_lines.c			# ok
#CFILES += ./ucgui394_sample/basic_hello1.c		# ok
#CFILES += ./ucgui394_sample/color_showcolorbar.c	# ok
#CFILES += ./ucgui394_sample/cursor_sample.c	# ok
#CFILES += ./ucgui394_sample/dashboard.c		# ok
CFILES += ./ucgui394_sample/dialog_all.c		# done
#CFILES += ./ucgui394_sample/housecontrol.c		# comiler error, need rtos.h
#CFILES += ./ucgui394_sample/memdev_autodev.c	# ok
#CFILES += ./ucgui394_sample/memdev_banding.c	# ok
#CFILES += ./ucgui394_sample/memdev_memdev.c		# ok
#CFILES += ./ucgui394_sample/mt_multitasking.c	# not run
#CFILES += ./ucgui394_sample/touch_sample.c		# ok
#CFILES += ./ucgui394_sample/widget_buttonround.c	# ok
#CFILES += ./ucgui394_sample/widget_edit.c		# ok
#CFILES += ./ucgui394_sample/widget_listboxownerdraw.c	# ok
#CFILES += ./ucgui394_sample/widget_listview.c	# ok
#CFILES += ./ucgui394_sample/widget_framewin.c	# ok
#CFILES += ./ucgui394_sample/widget_header.c	# ok
#CFILES += ./ucgui394_sample/widget_scrollbarmove.c	# ok
#CFILES += ./ucgui394_sample/widget_simplelistbox.c	# ok
#CFILES += ./ucgui394_sample/widget_simpleprogbar.c	# ok
#CFILES += ./ucgui394_sample/wm_redraw.c	# ok
#CFILES += ./ucgui394_sample/wm_sample.c	# done
#CFILES += ./ucgui394_sample/xeye.c			# ok
#CFILES += ./ucgui394_sample/sim_hardkey.c	# comiler error, need sim.h
#CFILES += ./ucgui394_sample/memdev_drawgraph.c		# failue
#CFILES += ./ucgui394_sample/font_Shiftjis.c		# done
#CFILES += ./ucgui394_sample/dialog_slidercolor.c	# done
#CFILES += ./ucgui394_sample/dialog_radio.c			# ok
#CFILES += ./ucgui394_sample/dialog_messagebox.c	# ok

